### ISSUE TITLE
HTTP Client Standard Library

### ISSUE THREAD

**Issue by AlenSaito1** [Synthesized-Infinity/Ethereal#2]
Implement a standard library which provides an interface for fetching resources across networks similar to JavaScript's [fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API)

**Comment by OHNONOTAMOTH** [comment]
will this work?
`
use reqwest::blocking;

fn gethttp(i: String) -> Result<String, reqwest::Error> {
    let h = reqwest::blocking::get()?.text();
    return h;
}
`

**Comment by AlenSaito1** [comment]
Yes, Something like this parsed with `Object::x(y)` as return value.

**Comment by OHNONOTAMOTH** [comment]
`fn webget(i: String) -> Object::string {
    return gethttp(i);
}

fn gethttp(i: String) -> Result<String, reqwest::Error> {
    let h = reqwest::blocking::get(i)?.text();
    return h;
`}

will this work?
